name: Jagwar - Down
favicon: null
layout_spectrum: 0.25047
typography_spectrum: 0.66056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2a2a'
    - '#ffffff'
    - '#434343'
    - '#afafaf'
    - '#696969'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: awareness
    item: null
    url: null
