name: null
favicon: null
layout_spectrum: 0.05743
typography_spectrum: 0.73888
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2a2a'
    - '#ffffff'
    - '#434343'
    - '#afafaf'
    - '#696969'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: null
    url: null
